# Generated by Django 4.2.10 on 2026-06-22 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('district', models.CharField(choices=[('chaoyang', '朝阳区'), ('haidian', '海淀区'), ('xicheng', '西城区'), ('dongcheng', '东城区'), ('fengtai', '丰台区'), ('shijingshan', '石景山区'), ('tongzhou', '通州区'), ('changping', '昌平区'), ('daxing', '大兴区'), ('yizhuang', '亦庄')], max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_type', models.CharField(choices=[('1', '一室'), ('2', '两室'), ('3', '三室'), ('4', '四室及以上')], max_length=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('orientation', models.CharField(blank=True, max_length=50)),
                ('decoration', models.CharField(blank=True, max_length=100)),
                ('facilities', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('rented', '已出租')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '房源',
                'verbose_name_plural': '房源',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='properties.property')),
            ],
            options={
                'verbose_name': '租赁申请',
                'verbose_name_plural': '租赁申请',
                'db_table': 'rental_applications',
            },
        ),
    ]
